### ISSUE TITLE
Image editing

### ISSUE THREAD

**Issue by greecehalf** [ziqihuangg/Collaborative-Diffusion#1]
Could you release the instruction for image editing?

**Comment by Muhammad-Huzaifaa** [comment]
Can you please release the code for image editing?

**Comment by ziqihuangg** [comment]
Hi, thanks for your patience, and I'll probably organize the instructions and code of Image Editing for release in June. 

Actually you can use the trained dynamic diffusers to collaborate existing diffusion-based image editing methods. The collaboration is done during sampling time, and is orthogonal to the image editing method. (We used Imagic as the editing method in our paper.)

**Comment by Liu-Yin** [comment]
Could you please release the code for image editing? This idea is amazing and I can‘t wait to run this code. Thx a lot!

**Comment by zhouwy19** [comment]
Amazing work! Is there an update here?

**Comment by leonardodora** [comment]
> @Liu-Yin Thanks for your interest. I'm a bit occupied lately, and I will try to release the editing code later this month.

hi, Is there any plan to release the image edting code. Thanks for your reply!

**Comment by ziqihuangg** [comment]
Hi, see here for image editing: https://github.com/ziqihuangg/Collaborative-Diffusion#editing
