### ISSUE TITLE
pre-processed data

### ISSUE THREAD

**Issue by wxqlab** [ziqihuangg/Collaborative-Diffusion#10]
Hi~,
could you provide the code of how to get the pre-processed data, i.e., the mask image (0.pt, 1.pt, ...) files.
Thank you very much!

**Comment by ziqihuangg** [comment]
Hi, the pre-processed data is provided here: https://drive.google.com/drive/folders/1rLcdN-VctJpW4k9AfSXWk0kqxh329xc4?usp=sharing

**Comment by BigcowPeking** [comment]
could you provide the code of how to get the pre-processed data, i.e., the mask image (0.pt, 1.pt, ...) files, we want to train our datasets, Thank you very much!
