### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by haizhu12** [ziqihuangg/Collaborative-Diffusion#12]
Hi, I'm running the training text-image model on an RTX3090 GPU with this error, "Hi, I'm running the training text-image model on an RTX3090 GPU with this error, "(cpu)"
python 3.11 pytorch:2.0.1 cuda:11.7
![2023-07-26 14-42-07屏幕截图](https://github.com/ziqihuangg/Collaborative-Diffusion/assets/93024130/e26df8bb-e2dc-4b3c-8050-32b6fd79a5b2)

**Comment by zhouwy19** [comment]
I also meet this problem. Have you solved it?

**Comment by chaunceywx** [comment]
Excuse me, have you solved this problem?

**Comment by chaunceywx** [comment]
> I also meet this problem. Have you solved it?

Excuse me, have you solved this problem?
