### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by zhouwy19** [ziqihuangg/Collaborative-Diffusion#13]
Hi,

Thank you for your nice work.

I would like to know the time required for their training, including vae, uni-modal and dynamic model.

I train the vae model for about 3 hours using 4 gpus.  But I still find the sampled image is poor.

![image](https://github.com/ziqihuangg/Collaborative-Diffusion/assets/43036573/d82d0e73-01fc-47d6-b643-60c00a1d1a35)

The recon image looks ok.

![image](https://github.com/ziqihuangg/Collaborative-Diffusion/assets/43036573/aefa84d0-ff13-4bf3-ac58-e1e0520916df)

**Comment by ziqihuangg** [comment]
Hi, you should sample using the diffusion UNet instead of directly from the VAE latents. The VAE here is mainly for spatial compression purposes. Diffusion UNet is the main one that takes care of the image distribution.

**Comment by zhouwy19** [comment]
Do you mean these default outputs are useless？

![image](https://github.com/ziqihuangg/Collaborative-Diffusion/assets/43036573/e6da24bc-c241-45ee-af07-9f66459db687)

**Comment by ziqihuangg** [comment]
For the VAE here, you should look at `reconstructions_gs-xxxxxx` to assess the training progress. I would say you don't need to look at `samples_gs-xxxxx`, but it can give you a sense of what images look like if you directly sample from the VAE latents without using the diffusion UNet.
