### ISSUE TITLE
missing pretrained model 256_text.ckpt

### ISSUE THREAD

**Issue by leonardodora** [ziqihuangg/Collaborative-Diffusion#14]
thanks for your updates! amazing work!
But it seems there is no 256_text.ckpt in google driver.
Could you please upload one?

**Comment by ziqihuangg** [comment]
Hi, thanks for letting me know. I've just uploaded the 256_text.ckpt.

**Comment by leonardodora** [comment]
> Hi, thanks for letting me know. I've just uploaded the 256_text.ckpt.

thanks for that!
