### ISSUE TITLE
any script for single modal generation?

### ISSUE THREAD

**Issue by zhouwy19** [ziqihuangg/Collaborative-Diffusion#15]
Hi, is there any script for single modal generation?

**Comment by ziqihuangg** [comment]
Hi, I just added scripts for face generation driven by single modality:

- text-to-face: [https://github.com/ziqihuangg/Collaborative-Diffusion#text-to-face-generation](url) 
- mask-to-face: [https://github.com/ziqihuangg/Collaborative-Diffusion#mask-to-face-generation](url)
