### ISSUE TITLE
about the cross attention in Dynamic Diffuser

### ISSUE THREAD

**Issue by chensming** [ziqihuangg/Collaborative-Diffusion#2]
Hi, you have done a nice work. I 'm interested in your work but I wonder why can we do cross attention between the feature of the x_t and the context.

context: mask -(resize)-> [bz, 32, 32] -(one hot)-> [bz, 19, 32, 32] -(flattern)-> [bz, 19, 1024] -(linear layer)-> [bz, 19, 640]
https://github.com/ziqihuangg/Collaborative-Diffusion/blob/8e2e6d3acf6fab05f85196ac2bfc08c5d214ded6/ldm/modules/attention.py#L170
```python
def forward(self, x, context=None, mask=None):
        h = self.heads   # x.shape: [bz, 1024, 384], context.shape: [4, 19, 640]

        q = self.to_q(x)         # q.shape: [bz, 1024, 384]
        context = default(context, x)
        k = self.to_k(context)   # k.shape: [bz, 19, 384]
        v = self.to_v(context)   # v.shape: [bz, 19, 384]

        q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> (b h) n d', h=h), (q, k, v)) # q.shape: [128, 1024, 12], k[128, 19, 12], v[128, 19, 12]

        sim = einsum('b i d, b j d -> b i j', q, k) * self.scale    # sim: [248, 1024, 19]

        if exists(mask):
            mask = rearrange(mask, 'b ... -> b (...)')
            max_neg_value = -torch.finfo(sim.dtype).max
            mask = repeat(mask, 'b j -> (b h) () j', h=h)
            sim.masked_fill_(~mask, max_neg_value)

        # attention, what we cannot get enough of
        attn = sim.softmax(dim=-1)         # attn: [128, 1024, 19]

        out = einsum('b i j, b j d -> b i d', attn, v)   # out.shape: [128, 1024, 12]
        out = rearrange(out, '(b h) n d -> b n (h d)', h=h)   # out.shape: [4, 1024, 384]
        return self.to_out(out)
```

So why can we do cross attention between x_t(exactly z_t) and the feature of the mask, what does it mean?
Thank you very much if you could solve my problem.

**Comment by ziqihuangg** [comment]
Hi, cross-attention is to condition the image generation process on the conditions (e.g., text, mask ...). It is part of LDM. You can check the LDM paper Section 3.3 Conditional Mechanisms for more details. (https://arxiv.org/abs/2112.10752)
