### ISSUE TITLE
about Training Time

### ISSUE THREAD

**Issue by zhouwy19** [ziqihuangg/Collaborative-Diffusion#21]
It seems that max_epochs will default to 1000 for training single modal. And It costs about 25min for one epoch using 8 gpus. Does it mean it costs about 1000 * 25 / 60 / 24 ~ 17days for training text2img model?

**Comment by ziqihuangg** [comment]
[https://github.com/ziqihuangg/Collaborative-Diffusion/issues/17#issuecomment-1870890921](url)
