### ISSUE TITLE
Questions about differences between Multi-ControlNet

### ISSUE THREAD

**Issue by aryenchiu** [ziqihuangg/Collaborative-Diffusion#22]
Hi, thanks for your excellent work!
I understand that ControlNet was released after the CVPR 2023 deadline, but I'm curious about the differences between your work and Multi-ControlNet and any additional advantages in your work. It appears that Multi-ControlNet can also handle multi-modal generation.

**Comment by diamond0910** [comment]
I think they are the same task, but with different methods.

**Comment by ziqihuangg** [comment]
They are different approaches to the same task. The essence of the "Collaborative Diffusion" framework is how to make several pre-trained diffusion models "collaborate" together at inference time, and we use multi-modal-driven generation as an illustration.
