### ISSUE TITLE
Text-to-Face.

### ISSUE THREAD

**Issue by sxl142** [ziqihuangg/Collaborative-Diffusion#24]
Hi, great work. We find this code seems only work on your given text "This man has beard of medium length. He is in his thirties.". when i use "He doesn't have any bangs and has an extremely mild smile, no beard at all, and no glasses. this person is in the thirties.", the results are far from the given text. The results almost are female. So is there any bug here?

**Comment by diamond0910** [comment]
These attributes are not included in this repo training data.

**Comment by ziqihuangg** [comment]
Hi, the text label version we use contains the "age" and "beard" attributes, as other attributes like bangs or smile are already controllable by the segmentation mask.
