### ISSUE TITLE
Empty Condition for training unmodal image generation

### ISSUE THREAD

**Issue by Open-Debin** [ziqihuangg/Collaborative-Diffusion#26]
I am very interested in your work, thank you for sharing the codes of Collaborative Diffusion.
I have two questions, what is the empty condition when you train text/mask to image generation? If I understand correctly, for text-to-image generation, the empty condition is [""], as your code shows "uc = model.get_learned_conditioning(n_samples * [""])". However, it's the empty condition for training mask to image generation. Is it a zero mask? Thank you very much for your attention.

**Comment by ziqihuangg** [comment]
“if scale != 1.0:” is by default never true, so the “uc = model.get_learned_conditioning(n_samples * [""])” is never implemented. If you want to use classifier-free guidance, perhaps you can try all-zero tensor as the mask.
