### ISSUE TITLE
Which image shoulw I use in image editing

### ISSUE THREAD

**Issue by Open-Debin** [ziqihuangg/Collaborative-Diffusion#27]
![image](https://github.com/ziqihuangg/Collaborative-Diffusion/assets/52323137/d5bb4234-eafc-4f5d-9f0e-216d5ea25b90)
Hello Ziqi Huang, I am very interested in your work, thank you for sharing the codes of Collaborative Diffusion.
I am a little bit confused about the image editing results. I think 0C_interText_optDM_?_alpha is the generated result. But there are results from different alpha,  In this case, I think the image name "0C_interText_optDM_0_alpha=-1.0" should be the best one. But if you automatically select an image which alpha is possibly the best?

**Comment by ziqihuangg** [comment]
Thanks for the question. The final edited image is “f'0C_interText_optDM_{idx}_alpha={round(alpha,3)}.png'”. The optimal value of alpha might vary based on the input image --- In the Imagic paper, it says “the optimal η value may vary per input”.
