### ISSUE TITLE
Script for calculating quantitative metrics

### ISSUE THREAD

**Issue by diamond0910** [ziqihuangg/Collaborative-Diffusion#29]
Do you have a script for calculating quantitative metrics? For example, FID and text/mask alignment. Thank you!

**Comment by ziqihuangg** [comment]
Thanks for the questions. The details are available in our paper Section 4.3.

For FID, you can use https://github.com/mseitzer/pytorch-fid.
For text alignment, it's the standard CLIP similarity calculation, see https://github.com/openai/CLIP
For mask alignment, it's the pixel-wise accuracy against the ground-truth segmentation.
