### ISSUE TITLE
preprocessing code for sketch and mask

### ISSUE THREAD

**Issue by chaunceywx** [ziqihuangg/Collaborative-Diffusion#32]
I am very interested in your work, thank you for sharing the codes of Collaborative Diffusion. 

I want to generate images from my own sketch and mask. Could you share the preprocessing code for sketch and mask?

I noticed that sketches and masks you used are 19*1024 tensors, but the raw sketches and masks are 512x512 px images.

How can I convert my own mask or sketch from  512x512 px images to 19*1024 tensors? Can you give me some advice？

 Thank you very much!

**Comment by qklee-lz** [comment]
> I am very interested in your work, thank you for sharing the codes of Collaborative Diffusion.
> 
> I want to generate images from my own sketch and mask. Could you share the preprocessing code for sketch and mask?
> 
> I noticed that sketches and masks you used are 19*1024 tensors, but the raw sketches and masks are 512x512 px images.
> 
> How can I convert my own mask or sketch from 512x512 px images to 19*1024 tensors? Can you give me some advice？
> 
> Thank you very much!

Do you know how to preprocess it?

**Comment by chaunceywx** [comment]
> > I am very interested in your work, thank you for sharing the codes of Collaborative Diffusion.
> > I want to generate images from my own sketch and mask. Could you share the preprocessing code for sketch and mask?
> > I noticed that sketches and masks you used are 19*1024 tensors, but the raw sketches and masks are 512x512 px images.
> > How can I convert my own mask or sketch from 512x512 px images to 19*1024 tensors? Can you give me some advice？
> > Thank you very much!
> 
> Do you know how to preprocess it?

I've given up

**Comment by ziqihuangg** [comment]
You can find the preprocessing code here: https://github.com/ziqihuangg/Collaborative-Diffusion/blob/master/mask2image.py#L111-L123

**Comment by chaunceywx** [comment]
> You can find the preprocessing code here: https://github.com/ziqihuangg/Collaborative-Diffusion/blob/master/mask2image.py#L111-L123

Does the preprocessing of the sketch employ the same method as the preprocessing of the mask?
