### ISSUE TITLE
Why does the text file only contain beard and age?

### ISSUE THREAD

**Issue by phil329** [ziqihuangg/Collaborative-Diffusion#34]
https://drive.google.com/drive/folders/1j8gcV5UyGoc-ylMxc7tCEzftL46ySdFE

**Comment by ziqihuangg** [comment]
This is because other information has been controlled by other modalities (e.g. face shape by mask, contours by sketch). To avoid potential conflicts, we use the attributes that are wouldn't cause potential conflict from the CelebA-Dialog Dataset.
