### ISSUE TITLE
details about dynamic diffuser and Influence Functions

### ISSUE THREAD

**Issue by CNGaoWenbo** [ziqihuangg/Collaborative-Diffusion#35]
Hi, in your paper seems no details about how dynamic diffuser works and how to get Influence Functions. can you provide more details? or the codes related to this part. Thank you

**Comment by ziqihuangg** [comment]
Hi, please see paper Section 3.2, and Supplementary File Section A.1 for details. Corresponding model definitions are available here: https://github.com/ziqihuangg/Collaborative-Diffusion/blob/master/ldm/models/diffusion/compose_modules.py Hope this clarifies.

**Comment by CNGaoWenbo** [comment]
thank you. From my understanding, the pre-trained seg_mask_unet outputs a generated picture at t, then feed this picture into the dynamic diffuser(seg_mask_confidence_predictor in codes). I understand that seg_mask_unet is trained, but the problem is I did not find how to train the seg_mask_confidence_predictor. Are seg_mask_confidence_predictor and seg_mask_unet the same unet model?

**Comment by ziqihuangg** [comment]
Hi, they are not the same UNet model. 
seg_mask_unet is a generative model, which generates a face image given a segmentation mask input.
seg_mask_confidence_predictor is the dynamic diffuser (a meta-network) which predicts how each collaborator (e.g., seg_mask_unet) contributes over the sampling process. As for how to train the dynamic diffuser, please refer to the Training "Algorithm" in our paper. If you still have questions, feel free to reach out.
