### ISSUE TITLE
ERROR:run “pip install git+https://github.com/arogozhnikov/einops.git”i

### ISSUE THREAD

**Issue by quleileileilei** [ziqihuangg/Collaborative-Diffusion#9]
when I run “pip install git+https://github.com/arogozhnikov/einops.git”in Linux on a remote server，

there appears a 
ERROR: Command errored out with exit status 128: git clone -q https://github.com/arogozhnikov/einops.git /tmp/pip-req-build-i3bwe_2t Check the logs for full command output.

How can I do？

**Comment by LisaLy123456** [comment]
You can use "pip install git+https://kgithub.com/arogozhnikov/einops.git" to replace it
